### ISSUE TITLE
 Does it work for C4D S24?

### ISSUE THREAD

**Issue by leikal** [AiMiDi/C4D_MMD_Tool#2]
Hi, does it work for version S24.037? I put the address of the plugin but it does not appear

こんにちは、バージョン S24.037 で動作しますか?プラグインのアドレスを入れたのに出てこない

私はスペイン語を話すので、翻訳機を使いました。

**Comment by AiMiDi** [comment]
You are not the only one who raised this issue, I am working hard to fix it, please wait a moment.        

Usted no es el único que planteó este problema, estoy trabajando duro para solucionarlo, espere un momento.
(traductor)

**Comment by AiMiDi** [comment]
I tried to fix the problem. I tested it with another computer and there was no problem. You can download and try it.

Traté de solucionar el problema. Lo probé con otra computadora y no hubo ningún problema. Puedes descargarlo y probarlo.
(traductor)

**Comment by leikal** [comment]
Now if it works, great! I appreciate your response and dedication.


うまくいったら、素晴らしいです!あなたの対応と献身に感謝します。

**Comment by leikal** [comment]
![Captura 2](https://user-images.githubusercontent.com/85371379/120895832-c56ada00-c5ec-11eb-866e-4a13d2e4e60d.png)
![Captura 1](https://user-images.githubusercontent.com/85371379/120895834-c7349d80-c5ec-11eb-9a03-59e8737c796b.png)

I was testing a movement with a model (2B) and this happens, it appears to me that it cannot find several bones and then when I try to reproduce the movement the lower part of the body gets stuck in the center.

I tried another movement and that does not happen, however now the problem is in the feet. I tried changing the scale of the character and movement and translating into English but I am not very knowledgeable on the subject. Maybe you can help me, am I doing something wrong?

モデル (2B) で動きをテストしていたところ、いくつかの骨が見つからないように見え、動きを再現しようとすると、下半身が中央で動かなくなってしまいました。

別の動きを試しましたが、それは起こりませんでしたが、今問題は足にあります。キャラクターや動きのスケールを変えて英語に翻訳してみましたが、あまり知識がありません。多分あなたは私を助けることができます、私は何か間違ったことをしていますか？

**Comment by leikal** [comment]
> ![Captura 2](https://user-images.githubusercontent.com/85371379/120895832-c56ada00-c5ec-11eb-866e-4a13d2e4e60d.png)
> ![Captura 1](https://user-images.githubusercontent.com/85371379/120895834-c7349d80-c5ec-11eb-9a03-59e8737c796b.png)
> 
> Estaba probando un movimiento con un modelo (2B) y esto pasa, me parece que no encuentra varios huesos y luego cuando trato de reproducir el movimiento la parte inferior del cuerpo se atora en el centro.
> 
> Probé otro movimiento y no pasa, sin embargo ahora el problema está en los pies. Intenté cambiar la escala del personaje y el movimiento y traducir al inglés, pero no estoy muy bien informado sobre el tema. Tal vez puedas ayudarme, ¿estoy haciendo algo mal?
> 
> モ デ ル (2B) で 動 き を テ ス ト し て い た と こ ろ 、 い く つ か の 骨 が 見 つ か ら な い よ に 見 え 、 、 動 き を 再現 し よ う う と す
> 
> 別 の 動 き を 試 し ま し た が, そ れ は 起 こ り ま せ ん で し た が, 今 問題 は 足 に あ り ま す. キ ャ ラ ク タ ー や 動 き の ス ケ ー ル を 変 え て 英語 に 翻 訳 し て み ま し た が, あ ま り 知識 が あ り ま せ ん. 多分 あ な た は 私を 助 け る こ と が で き ま す 、 私 は 何 か 間 違 っ た こ と を し て い ま す か？



> ![Captura 2](https://user-images.githubusercontent.com/85371379/120895832-c56ada00-c5ec-11eb-866e-4a13d2e4e60d.png)
> ![Captura 1](https://user-images.githubusercontent.com/85371379/120895834-c7349d80-c5ec-11eb-9a03-59e8737c796b.png)
> 
> I was testing a movement with a model (2B) and this happens, it appears to me that it cannot find several bones and then when I try to reproduce the movement the lower part of the body gets stuck in the center.
> 
> I tried another movement and that does not happen, however now the problem is in the feet. I tried changing the scale of the character and movement and translating into English but I am not very knowledgeable on the subject. Maybe you can help me, am I doing something wrong?
> 
> モデル (2B) で動きをテストしていたところ、いくつかの骨が見つからないように見え、動きを再現しようとすると、下半身が中央で動かなくなってしまいました。
> 
> 別の動きを試しましたが、それは起こりませんでしたが、今問題は足にあります。キャラクターや動きのスケールを変えて英語に翻訳してみましたが、あまり知識がありません。多分あなたは私を助けることができます、私は何か間違ったことをしていますか？

**Comment by leikal** [comment]
追加情報として、ムーブメントは Apple Pie であり、MMD とブレンダーで動作することがよく知られています。
As additional information, the movement is an Apple Pie and is well known to work with MMD and blender

**Comment by AiMiDi** [comment]
This may be related to the action and the model, and there may be missing relevant bones. Please upload the action and model in question and let me test what the problem is.

Esto puede estar relacionado con la acción y el modelo, y puede haber una falta de huesos relevantes. Sube la acción y el modelo en cuestión y déjame probar cuál es el problema.

**Comment by leikal** [comment]
Thanks for your reply, 
You can download the model from the official website here: http://tstorage.info/jtum9duyxij8
and the motion dance: http://www.mediafire.com/file/br9y9nx16tlzja3/Apple_Pie_-_by__Ademar440.rar/file

**Comment by leikal** [comment]
> Thanks for your reply,
> You can download the model from the official website here: http://tstorage.info/jtum9duyxij8
> and the motion dance: http://www.mediafire.com/file/br9y9nx16tlzja3/Apple_Pie_-_by__Ademar440.rar/file

As I mentioned before, I have tested the model and this movement before and there have been no problems, but I have never done it in cinema

**Comment by AiMiDi** [comment]
After testing, I think this is a problem with the motion file, because it tries to add a moving animation to a bone that can only rotate. My plug-in did not stop him. I will fix it in the next version.
![image](https://user-images.githubusercontent.com/76622021/120912233-1b5c8200-c6c0-11eb-8e15-ef8da84e3f50.png)
(This should not be able to be moved)

 At the same time, I found that it did not import the skeleton skin animation, and it will be merged and repaired in the next version. 
![image](https://user-images.githubusercontent.com/76622021/120912308-9faf0500-c6c0-11eb-9130-43c2cbc8e229.png)
(This should have imported animation)

Thank you for the question.
In addition, I am Chinese.

Después de la prueba, creo que esto es un problema con el archivo de movimiento, porque intenta agregar una animación en movimiento a un hueso que solo puede girar. Mi complemento no lo detuvo. Lo solucionaré en la próxima versión. 
Al mismo tiempo, descubrí que no importaba la animación de máscara de esqueleto, y se fusionará y reparará en la próxima versión. 
Gracias por la pregunta. 
Además, soy chino.

**Comment by leikal** [comment]
我明白了，谢谢。我会等你的新版本

I understand, thank you. I will wait for your new version

**Comment by AiMiDi** [comment]
![image](https://user-images.githubusercontent.com/76622021/121390516-0b72c580-c980-11eb-96e0-6be6ed4f5a10.png)
After several days of modification, I think there is only one problem that can only be solved manually. This is a problem with the motion data. If you encounter this problem, please manually delete the animation track of this bone.

Después de varios días de modificación, creo que solo hay un problema que solo se puede resolver manualmente. Este es un problema con los datos de movimiento. Si encuentra este problema, elimine manualmente la pista de animación de este hueso.
